=== UnusAnnusArchived/TUAA-Frontend-NextJs/metadata/_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "type": "object",
  "properties": {
    "_metadataVersion": {
      "type": "number",
      "enum": [3]
    },
    "sources": {
      "type": "array",
      "items": {
        "oneOf": [
          {
            "type": "object",
            "properties": {
              "type": {
                "type": "string",
                "enum": ["bunny"]
              },
              "bunnyId": {
                "type": "string",
                "pattern": "^[0-9a-fA-F]{8}\\b-[0-9a-fA-F]{4}\\b-[0-9a-fA-F]{4}\\b-[0-9a-fA-F]{4}\\b-[0-9a-fA-F]{12}$"
              }
            },
            "required": ["type", "bunnyId"]
          },
          {
            "type": "object",
            "properties": {
              "type": {
                "type": "string",
                "enum": ["direct"]
              },
              "name": {
                "type": "string"
              },
              "id": {
                "type": "string"
              },
              "resolutions": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "src": {
                      "type": "string",
                      "pattern": "https?:\\/\\/(www\\.)?[-a-zA-Z0-9@:%._\\+~#=]{1,256}\\.[a-zA-Z0-9()]{1,6}\\b([-a-zA-Z0-9()!@:%_\\+.~#?&\\/\\/=]*)"
                    },
                    "width": {
                      "type": "number",
                      "minimum": 1
                    }
                  },
                  "required": ["src", "width"]
                }
              }
            },
            "required": ["type", "name", "id", "resolutions"]
          },
          {
            "type": "object",
            "properties": {
              "type": {
                "type": "string",
                "enum": ["youtube"]
              },
              "youtubeId": {
                "type": "string",
                "pattern": "^[\\w\\d_\\-]{11}$"
              }
            },
            "required": ["type", "youtubeId"]
          }
        ]
      }
    },
    "uaid": {
      "type": "string",
      "pattern": "^s\\d{2}.e\\d{3}$"
    },
    "season": {
      "type": "number",
      "minimum": 0
    },
    "episode": {
      "type": "number",
      "minimum": 1
    },
    "title": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "releaseDate": {
      "type": "number",
      "minimum": 0
    },
    "isLast": {
      "type": "boolean"
    }
  },
  "required": ["_metadataVersion", "sources", "uaid", "season", "episode", "title", "description", "releaseDate"]
}

=== UnusAnnusArchived/TUAA-Frontend-NextJs/metadata/01/185.json
{
  "$schema": "../_schema.json",
  "_metadataVersion": 3,
  "sources": [
    {
      "type": "bunny",
      "bunnyId": "81b1bdce-3a32-40cc-8e0a-c2c2cb69d2ff"
    }
  ],
  "uaid": "s01.e185",
  "season": 1,
  "episode": 185,
  "title": "We Explore the Unus Annus Subreddit for Your Delicious Memes",
  "description": "Once again, we look at all the wonderful, funny, and downright disturbing memes you fine folks have posted on the Unus Annus Subreddit.",
  "releaseDate": 1589655600000
}

=== UnusAnnusArchived/TUAA-Frontend-NextJs/metadata/01/261.json
{
  "$schema": "../_schema.json",
  "_metadataVersion": 3,
  "sources": [
    {
      "type": "bunny",
      "bunnyId": "e74b9d40-107d-4a55-a8b2-a219eb77b16e"
    }
  ],
  "uaid": "s01.e261",
  "season": 1,
  "episode": 261,
  "title": "Recharging Our Phones Using Only Brute Strength",
  "description": "",
  "releaseDate": 1596135600000
}

=== UnusAnnusArchived/TUAA-Frontend-NextJs/metadata/01/047.json
{
  "$schema": "../_schema.json",
  "_metadataVersion": 3,
  "sources": [
    {
      "type": "bunny",
      "bunnyId": "ee2327a5-24a0-402f-97b4-8304a13849c3"
    }
  ],
  "uaid": "s01.e047",
  "season": 1,
  "episode": 47,
  "title": "You Blink You Lose",
  "description": "The eyes are the window into the soul. You better not look away... you might miss something.<br>PEEN ►<a target=\"blank\" href=\"https://youtu.be/553CfZAADag\">https://youtu.be/553CfZAADag</a><br><br>Edited by  ► <a target=\"blank\" href=\"http://www.youtube.com/crankgameplays\">http://www.youtube.com/crankgameplays</a><br><br>This channel, along with every video that has or will ever be uploaded on this channel, will be deleted after our year has ended. This is inevitable. Inescapable. Irreversible.<br>Do not archive or re-upload anything. This is our last wish. Our parting gift. Stay true to the purpose of our final year or we shall lay down wrath upon those that attempt to escape the end.<br><br>Memento Mori.<br>Unus Annus.",
  "releaseDate": 1577732400000
}

=== UnusAnnusArchived/TUAA-Frontend-NextJs/metadata/00/016.json
{
  "$schema": "../_schema.json",
  "_metadataVersion": 3,
  "sources": [
    {
      "type": "bunny",
      "id": "bunny",
      "bunnyId": "37c35e26-87e0-4339-910b-ac8b3066349e"
    },
    {
      "type": "youtube",
      "id": "youtube",
      "name": "YouTube",
      "youtubeId": "Lvicaufi5O0"
    }
  ],
  "uaid": "s00.e016",
  "season": 0,
  "episode": 16,
  "title": "Mori",
  "description": "Memento â–º <a href=\"https://unusann.us/watch/s00.e015\">https://youtu.be/yGxOsZOyyRg</a>",
  "releaseDate": 1668369720000
}

=== UnusAnnusArchived/TUAA-Frontend-NextJs/metadata/01/364.json
{
  "$schema": "../_schema.json",
  "_metadataVersion": 3,
  "sources": [
    {
      "type": "bunny",
      "id": "bunny",
      "bunnyId": "bc9e882c-8aab-4024-bfec-8f3fb9bc6812"
    }
  ],
  "uaid": "s01.e364",
  "season": 1,
  "episode": 364,
  "title": "Everything's Legal If You're Dead",
  "description": "Mark and Ethan start one of the last day of their lives off right with a healthy wholesome breakfast. And a whole bunch of crime.",
  "releaseDate": 1605034800000
}

=== UnusAnnusArchived/TUAA-Frontend-NextJs/metadata/01/004.json
{
  "$schema": "../_schema.json",
  "_metadataVersion": 3,
  "sources": [
    {
      "type": "bunny",
      "id": "bunny",
      "bunnyId": "6dbc4ea0-e55b-4ee0-a7e1-5de841931a08"
    }
  ],
  "uaid": "s01.e004",
  "season": 1,
  "episode": 4,
  "title": "Hot Dog’d to Death",
  "description": "The boys chase their dreams of joining Joey Chestnut in the MLE hall of fame.<br><br>Edited by Amy ► <a target=\"blank\" href=\"https://twitter.com/iceddarkroast\">https://twitter.com/iceddarkroast</a><br><br>This channel, along with every video that has or will ever be uploaded on this channel, will be deleted after our year has ended. This is inevitable. Inescapable. Irreversible.<br>Do not archive or re-upload anything. This is our last wish. Our parting gift. Stay true to the purpose of our final year or we shall lay down wrath upon those that attempt to escape the end.<br><br>Memento Mori.<br>Unus Annus.",
  "releaseDate": 1574017200000
}

=== UnusAnnusArchived/TUAA-Frontend-NextJs/metadata/01/065.json
{
  "$schema": "../_schema.json",
  "_metadataVersion": 3,
  "sources": [
    {
      "type": "bunny",
      "id": "bunny",
      "bunnyId": "70f1b31a-f801-4d77-945a-e51414437bf0"
    }
  ],
  "uaid": "s01.e065",
  "season": 1,
  "episode": 65,
  "title": "2 Absolute Beginners Experience the Dancing Glory that is Salsa",
  "description": "Salsa is the ancient art of dance whereby the dancers express thoughts and emotions through the undulations of their hips. We attempt to learn the mysterious ways of this sanctified dance.<br><br>Edited By â–º <a target=\"blank\" href=\"https://www.youtube.com/LixianTV\">https://www.youtube.com/LixianTV</a><br><br>This channel, along with every video that has or will ever be uploaded on this channel, will be deleted after our year has ended. This is inevitable. Inescapable. Irreversible.<br>Do not archive or re-upload anything. This is our last wish. Our parting gift. Stay true to the purpose of our final year or we shall lay down wrath upon those that attempt to escape the end.<br><br>Memento Mori.<br>Unus Annus.",
  "releaseDate": 1579287600000
}

=== UnusAnnusArchived/TUAA-Frontend-NextJs/metadata/01/085.json
{
  "$schema": "../_schema.json",
  "_metadataVersion": 3,
  "sources": [
    {
      "type": "bunny",
      "id": "bunny",
      "bunnyId": "38b283f6-2a7e-41e2-b5c4-8b0a9f1ad085"
    }
  ],
  "uaid": "s01.e085",
  "season": 1,
  "episode": 85,
  "title": "Literally Eating Fire ",
  "description": "Yes, you read that right. Mark and Ethan learn how to literally eat fire. Don't try this at home.",
  "releaseDate": 1581015600000
}
