=== UnusAnnusArchived/TUAA-Frontend-NextJs/metadata/_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "type": "object",
  "properties": {
    "_metadataVersion": {
      "type": "number",
      "enum": [3]
    },
    "sources": {
      "type": "array",
      "items": {
        "oneOf": [
          {
            "type": "object",
            "properties": {
              "type": {
                "type": "string",
                "enum": ["bunny"]
              },
              "bunnyId": {
                "type": "string",
                "pattern": "^[0-9a-fA-F]{8}\\b-[0-9a-fA-F]{4}\\b-[0-9a-fA-F]{4}\\b-[0-9a-fA-F]{4}\\b-[0-9a-fA-F]{12}$"
              }
            },
            "required": ["type", "bunnyId"]
          },
          {
            "type": "object",
            "properties": {
              "type": {
                "type": "string",
                "enum": ["direct"]
              },
              "name": {
                "type": "string"
              },
              "id": {
                "type": "string"
              },
              "resolutions": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "src": {
                      "type": "string",
                      "pattern": "https?:\\/\\/(www\\.)?[-a-zA-Z0-9@:%._\\+~#=]{1,256}\\.[a-zA-Z0-9()]{1,6}\\b([-a-zA-Z0-9()!@:%_\\+.~#?&\\/\\/=]*)"
                    },
                    "width": {
                      "type": "number",
                      "minimum": 1
                    }
                  },
                  "required": ["src", "width"]
                }
              }
            },
            "required": ["type", "name", "id", "resolutions"]
          },
          {
            "type": "object",
            "properties": {
              "type": {
                "type": "string",
                "enum": ["youtube"]
              },
              "youtubeId": {
                "type": "string",
                "pattern": "^[\\w\\d_\\-]{11}$"
              }
            },
            "required": ["type", "youtubeId"]
          }
        ]
      }
    },
    "uaid": {
      "type": "string",
      "pattern": "^s\\d{2}.e\\d{3}$"
    },
    "season": {
      "type": "number",
      "minimum": 0
    },
    "episode": {
      "type": "number",
      "minimum": 1
    },
    "title": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "releaseDate": {
      "type": "number",
      "minimum": 0
    },
    "isLast": {
      "type": "boolean"
    }
  },
  "required": ["_metadataVersion", "sources", "uaid", "season", "episode", "title", "description", "releaseDate"]
}

=== UnusAnnusArchived/TUAA-Frontend-NextJs/metadata/01/108.json
{
  "$schema": "../_schema.json",
  "_metadataVersion": 3,
  "sources": [
    {
      "type": "bunny",
      "bunnyId": "9beae927-41d5-48a1-8be0-607561abb3dd"
    }
  ],
  "uaid": "s01.e108",
  "season": 1,
  "episode": 108,
  "title": "Top 10 Worst Things Your Friend Could Possibly Spend Their Money On ",
  "description": "Ethan is back at it again. His sleigh filled to the brim with horrible, horrible gifts to give his lovely friend Mark.<br>",
  "releaseDate": 1583002800000
}

=== UnusAnnusArchived/TUAA-Frontend-NextJs/metadata/01/104.json
{
  "$schema": "../_schema.json",
  "_metadataVersion": 3,
  "sources": [
    {
      "type": "bunny",
      "bunnyId": "c8979f52-c611-4f1d-8e1d-01b769ae312f"
    }
  ],
  "uaid": "s01.e104",
  "season": 1,
  "episode": 104,
  "title": "Long Hair, Do We Dare? ",
  "description": "Beauty. We love it. We live it. We ARE it. Let's make some moves to get that hair longer than life",
  "releaseDate": 1582657200000
}

=== UnusAnnusArchived/TUAA-Frontend-NextJs/metadata/01/033.json
{
  "$schema": "../_schema.json",
  "_metadataVersion": 3,
  "sources": [
    {
      "type": "bunny",
      "id": "bunny",
      "bunnyId": "8a2e1f7e-4bf1-453b-8409-e6c67eb06d95"
    }
  ],
  "uaid": "s01.e033",
  "season": 1,
  "episode": 33,
  "title": "We Had To Drink Each Other’s Pee",
  "description": "Through the power of the Life Straw, Ethan and Mark taste each other's urine.<br><br>Edited by  ► <a target=\"blank\" href=\"http://www.youtube.com/crankgameplays\">http://www.youtube.com/crankgameplays</a><br><br>This channel, along with every video that has or will ever be uploaded on this channel, will be deleted after our year has ended. This is inevitable. Inescapable. Irreversible.<br>Do not archive or re-upload anything. This is our last wish. Our parting gift. Stay true to the purpose of our final year or we shall lay down wrath upon those that attempt to escape the end.<br><br>Memento Mori.<br>Unus Annus.",
  "releaseDate": 1576522800000
}

=== UnusAnnusArchived/TUAA-Frontend-NextJs/metadata/01/064.json
{
  "$schema": "../_schema.json",
  "_metadataVersion": 3,
  "sources": [
    {
      "type": "bunny",
      "id": "bunny",
      "bunnyId": "7c09c0b3-7a88-4779-bd5b-8ff956346dae"
    }
  ],
  "uaid": "s01.e064",
  "season": 1,
  "episode": 64,
  "title": "You Breathe You Die",
  "description": "The rules are simple: You Breathe, You Die.<br><br>Edited by  â–º <a target=\"blank\" href=\"https://bit.ly/2Mv5aTM\">https://bit.ly/2Mv5aTM</a><br><br>This channel, along with every video that has or will ever be uploaded on this channel, will be deleted after our year has ended. This is inevitable. Inescapable. Irreversible.<br>Do not archive or re-upload anything. This is our last wish. Our parting gift. Stay true to the purpose of our final year or we shall lay down wrath upon those that attempt to escape the end.<br><br>Memento Mori.<br>Unus Annus.",
  "releaseDate": 1579201200000
}

=== UnusAnnusArchived/TUAA-Frontend-NextJs/metadata/01/190.json
{
  "$schema": "../_schema.json",
  "_metadataVersion": 3,
  "sources": [
    {
      "type": "bunny",
      "id": "bunny",
      "bunnyId": "9558f394-b118-4293-816e-cf09c03bd4a9"
    }
  ],
  "uaid": "s01.e190",
  "season": 1,
  "episode": 190,
  "title": "Harnessing Our Yodeling Power to End The World As We Know It",
  "description": "You hear that? Off in the distance? That, my friends, is the sound of two gods screaming into the ether. It is the first sound in the morning and the last sound at night. It is the call to end all calls. It is... THE YODEL.",
  "releaseDate": 1590087600000
}

=== UnusAnnusArchived/TUAA-Frontend-NextJs/metadata/01/102.json
{
  "$schema": "../_schema.json",
  "_metadataVersion": 3,
  "sources": [
    {
      "type": "bunny",
      "id": "bunny",
      "bunnyId": "ee08fd56-aac5-4fe5-bc0c-c99971491108"
    }
  ],
  "uaid": "s01.e102",
  "season": 1,
  "episode": 102,
  "title": "Edible Slime was a Mistake. ",
  "description": "Make the slime. Play with the slime. CONSUME the slime. Last we saw, the boys were unwilling to even touch the slime. Today they must eat it.",
  "releaseDate": 1582484400000
}

=== UnusAnnusArchived/TUAA-Frontend-NextJs/metadata/01/360.json
{
  "$schema": "../_schema.json",
  "_metadataVersion": 3,
  "sources": [
    {
      "type": "bunny",
      "id": "bunny",
      "bunnyId": "ed1796a2-cdbd-4a06-a35d-ed287db272a2"
    }
  ],
  "uaid": "s01.e360",
  "season": 1,
  "episode": 360,
  "title": "Whoâ€™s Cutting Onions In Here???",
  "description": "Only REAL men cry. And today we cry a lot. ",
  "releaseDate": 1604689200000
}

=== UnusAnnusArchived/TUAA-Frontend-NextJs/metadata/01/324.json
{
  "$schema": "../_schema.json",
  "_metadataVersion": 3,
  "sources": [
    {
      "type": "bunny",
      "id": "bunny",
      "bunnyId": "e1f8c3cf-007c-4ea0-ba81-6332a86ee90a"
    }
  ],
  "uaid": "s01.e324",
  "season": 1,
  "episode": 324,
  "title": "This Video Went Completely Out of Control",
  "description": "",
  "releaseDate": 1601578800000
}
