=== UnusAnnusArchived/TUAA-Frontend-NextJs/metadata/_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "type": "object",
  "properties": {
    "_metadataVersion": {
      "type": "number",
      "enum": [3]
    },
    "sources": {
      "type": "array",
      "items": {
        "oneOf": [
          {
            "type": "object",
            "properties": {
              "type": {
                "type": "string",
                "enum": ["bunny"]
              },
              "bunnyId": {
                "type": "string",
                "pattern": "^[0-9a-fA-F]{8}\\b-[0-9a-fA-F]{4}\\b-[0-9a-fA-F]{4}\\b-[0-9a-fA-F]{4}\\b-[0-9a-fA-F]{12}$"
              }
            },
            "required": ["type", "bunnyId"]
          },
          {
            "type": "object",
            "properties": {
              "type": {
                "type": "string",
                "enum": ["direct"]
              },
              "name": {
                "type": "string"
              },
              "id": {
                "type": "string"
              },
              "resolutions": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "src": {
                      "type": "string",
                      "pattern": "https?:\\/\\/(www\\.)?[-a-zA-Z0-9@:%._\\+~#=]{1,256}\\.[a-zA-Z0-9()]{1,6}\\b([-a-zA-Z0-9()!@:%_\\+.~#?&\\/\\/=]*)"
                    },
                    "width": {
                      "type": "number",
                      "minimum": 1
                    }
                  },
                  "required": ["src", "width"]
                }
              }
            },
            "required": ["type", "name", "id", "resolutions"]
          },
          {
            "type": "object",
            "properties": {
              "type": {
                "type": "string",
                "enum": ["youtube"]
              },
              "youtubeId": {
                "type": "string",
                "pattern": "^[\\w\\d_\\-]{11}$"
              }
            },
            "required": ["type", "youtubeId"]
          }
        ]
      }
    },
    "uaid": {
      "type": "string",
      "pattern": "^s\\d{2}.e\\d{3}$"
    },
    "season": {
      "type": "number",
      "minimum": 0
    },
    "episode": {
      "type": "number",
      "minimum": 1
    },
    "title": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "releaseDate": {
      "type": "number",
      "minimum": 0
    },
    "isLast": {
      "type": "boolean"
    }
  },
  "required": ["_metadataVersion", "sources", "uaid", "season", "episode", "title", "description", "releaseDate"]
}

=== UnusAnnusArchived/TUAA-Frontend-NextJs/metadata/01/128.json
{
  "$schema": "../_schema.json",
  "_metadataVersion": 3,
  "sources": [
    {
      "type": "bunny",
      "bunnyId": "d7d46858-6319-4bdd-8827-779227626ae4"
    }
  ],
  "uaid": "s01.e128",
  "season": 1,
  "episode": 128,
  "title": "We Tried a Labor Pain Simulator",
  "description": "Mark and Ethan will never know the TRUE feeling of child labor, but today they attempt to simulate that miracle.",
  "releaseDate": 1584730800000
}

=== UnusAnnusArchived/TUAA-Frontend-NextJs/metadata/01/011.json
{
  "$schema": "../_schema.json",
  "_metadataVersion": 3,
  "sources": [
    {
      "type": "bunny",
      "bunnyId": "cfbea560-eedb-4ca3-a9ac-de4234805305"
    }
  ],
  "uaid": "s01.e011",
  "season": 1,
  "episode": 11,
  "title": "Baby Hands Operation",
  "description": "Mark and Ethan strap on their baby hands and get straight to their most important job: Saving lives.<br><br>Edited by Ethan â–º <a target=\"blank\" href=\"https://www.youtube.com/channel/UC2S7CGceq5tsuhcVyACdA3g\">https://www.youtube.com/channel/UC2S7CGceq5tsuhcVyACdA3g</a><br><br>This channel, along with every video that has or will ever be uploaded on this channel, will be deleted after our year has ended. This is inevitable. Inescapable. Irreversible.<br>Do not archive or re-upload anything. This is our last wish. Our parting gift. Stay true to the purpose of our final year or we shall lay down wrath upon those that attempt to escape the end.<br><br>Memento Mori.<br>Unus Annus.",
  "releaseDate": 1574622000000
}

=== UnusAnnusArchived/TUAA-Frontend-NextJs/metadata/01/006.json
{
  "$schema": "../_schema.json",
  "_metadataVersion": 3,
  "sources": [
    {
      "type": "bunny",
      "id": "bunny",
      "bunnyId": "3ad53ce0-2b0b-41cd-a3c3-2bd744f94c02"
    }
  ],
  "uaid": "s01.e006",
  "season": 1,
  "episode": 6,
  "title": "The Good Kind of Cupping ðŸ™‚",
  "description": "Speed Cup Stacking is a time honored tradition enjoyed by thousands across the globe. Mark and Ethan attempt to learn the ways of the cup to see if they can compete in the global cup arena.<br>The Winner â–º <a target=\"blank\" href=\"https://www.youtube.com/channel/UCaFmoZOqvJuhMy2aZJ8rOMw\">https://www.youtube.com/channel/UCaFmoZOqvJuhMy2aZJ8rOMw</a><br><br>Edited by Amy â–º <a target=\"blank\" href=\"https://twitter.com/iceddarkroast\">https://twitter.com/iceddarkroast</a><br><br>This channel, along with every video that has or will ever be uploaded on this channel, will be deleted after our year has ended. This is inevitable. Inescapable. Irreversible.<br>Do not archive or re-upload anything. This is our last wish. Our parting gift. Stay true to the purpose of our final year or we shall lay down wrath upon those that attempt to escape the end.<br><br>Memento Mori.<br>Unus Annus.",
  "releaseDate": 1574190000000
}

=== UnusAnnusArchived/TUAA-Frontend-NextJs/metadata/01/365.json
{
  "$schema": "../_schema.json",
  "_metadataVersion": 3,
  "sources": [
    {
      "type": "bunny",
      "id": "bunny",
      "bunnyId": "81894c50-0ef3-4fa9-ae22-90dc6da22aca"
    }
  ],
  "uaid": "s01.e365",
  "season": 1,
  "episode": 365,
  "title": "7 Minutes in Heaven | 7 Minutes in Hell",
  "description": "What awaits for us in the great beyond? ",
  "releaseDate": 1605121200000
}

=== UnusAnnusArchived/TUAA-Frontend-NextJs/metadata/01/277.json
{
  "$schema": "../_schema.json",
  "_metadataVersion": 3,
  "sources": [
    {
      "type": "bunny",
      "bunnyId": "8a3be8b2-fb51-4a83-bc27-a2a7ab105b4a"
    }
  ],
  "uaid": "s01.e277",
  "season": 1,
  "episode": 277,
  "title": "Momiplier Teaches Self-Defense",
  "description": "",
  "releaseDate": 1597518000000
}

=== UnusAnnusArchived/TUAA-Frontend-NextJs/metadata/01/237.json
{
  "$schema": "../_schema.json",
  "_metadataVersion": 3,
  "sources": [
    {
      "type": "bunny",
      "bunnyId": "13b071c2-bebf-452a-8ecb-dd88257c31c0"
    }
  ],
  "uaid": "s01.e237",
  "season": 1,
  "episode": 237,
  "title": "The Candy Bra Challenge",
  "description": "",
  "releaseDate": 1594062000000
}

=== UnusAnnusArchived/TUAA-Frontend-NextJs/metadata/01/199.json
{
  "$schema": "../_schema.json",
  "_metadataVersion": 3,
  "sources": [
    {
      "type": "bunny",
      "id": "bunny",
      "bunnyId": "2b86c493-c9f9-41a1-936a-35470db342e4"
    }
  ],
  "uaid": "s01.e199",
  "season": 1,
  "episode": 199,
  "title": "Only Watch from 2:15 to 6:11 --- DO NOT WATCH ANY OTHER PART OF THIS VIDEO",
  "description": "Annus has officially been declared the WINNER! Please skip to 2:15 to view Annus's glorious appreciation segment and cease watching at exactly 6:11. DO NOT WATCH ANY OTHER PART OF THE VIDEO. DO NOT.",
  "releaseDate": 1590778800000
}

=== UnusAnnusArchived/TUAA-Frontend-NextJs/metadata/01/221.json
{
  "$schema": "../_schema.json",
  "_metadataVersion": 3,
  "sources": [
    {
      "type": "bunny",
      "id": "bunny",
      "bunnyId": "6cde76be-0a55-4ed3-89d1-0a4d2a9da2fc"
    }
  ],
  "uaid": "s01.e221",
  "season": 1,
  "episode": 221,
  "title": "The Ultimate Paper Airplane Showdown",
  "description": "Today we hone an ancient craft passed down from generation to generation: The Art of the Paper Airplane",
  "releaseDate": 1592679600000
}
